### PR TITLE
Rutshuehuehue

### PR DESCRIPTION
**Pull request by sujayrittikar**

### CODE REVIEW

**Comment by sujayrittikar** [comment]
Please follow the directory structure of the repo, add all the files inside Day01 directory.

**Review by sujayrittikar — COMMENTED** [review]
add it to Day01 directory of repo

**Review by sujayrittikar — COMMENTED** [review]
Please check the existing question in the repo. Create a pull request and change files there.

**Comment by anuraggk1** [comment]
My directory structure is my directory structure
None of your directory structure

**Comment by sujayrittikar** [comment]
> My directory structure is my directory structure
> None of your directory structure

Your directory structure was shittier than that extremely funny dialogue.

**Pull request closed without merging**
